---
title: The Biggest Mistake a Consultant Makes (and how to avoid it)
author: Elena Juarez
date: '2020-02-02'
slug: the-biggest-mistake-a-consultant-makes-and-how-to-avoid-it
categories:
  - R
tags: []
description: ''
topics: []
---

If you have ever been a consultant for a company or individual, one of the first things you do when getting started is meet with your contact about the project you have been newly assigned to. You may walk into this meeting with feelings of excitement or maybe even nervousness. 
If you are a good consultant, in that meeting you will be taking notes, asking questions, and regurgitating information back to assure that you are understanding things correctly and fully. 

If you are doing this, you will probably leave this interaction feeling relatively confident in your understanding of the scope of the project. However comforting this feeling may be, it important not to make one of the mistakes that most consultants all-too-often make - not checking back in with your client as often as you should and not asking questions frequently enough. 

Although you may feel good about your project, you may bee fooled into thinking you got everything you need, and that you understand 100% what the expectations are, what the client wants, and the general nuances of the project. But too many times, half way through the time-span of a project, you find out some vital piece of information that changes things drastically. The gut reaction is to blame the client: “How could they not tell me this earlier?” “Why did they assume I knew this already?” “They should have mentioned this from the start.”

But at the end of the day, it is the consultant’s task to extract the information you need (including the information you don’t even know that exists). This is arguably the most important step in consulting, and what sets a true consultant apart from the rest. 

Some tips to avoid this mistake:
* Consider meeting more often than you initially anticipated 
* Ask probing questions (even if you think you know the answer)
* State exactly what data and documents you need from the client, why you need it, and set up a time-line of when you will get it
* Ask the client what their pain-points are
* Ask the client what they envision the final product to show or tell them
* Ask the client what, if any, expectations they have
* Touch base regularly to update on progress and make sure you are on the right track



